favicon: null
name: desianwar
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7204958330839872
  brandStrength: 0.6948706849943846
  rhythmicContrast: 0.6285938215442002
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.7374238988850266
typography_spectrum: 0.8411357102449983
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9426523
analytics:
  twitter: null
  google: null
  facebook: null
