layout_spectrum: 0.6736931
favicon: null
name: desianwar
purpose: []
analytics:
  facebook: null
  google: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  domain: null
  bucket: null
  version: null
color:
  brandStrength: 0.6948706849943846
  saturation: 0.7204958330839872
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.7374238988850266
  rhythmicContrast: 0.6285938215442002
typography_spectrum: 0.8411357102449983
