name: desianwar
favicon: null
layout_spectrum: 0.7354350928217173
typography_spectrum: 0.8411357102449983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6948706849943846
  lightness: 0.7374238988850266
  saturation: 0.7204958330839872
  rhythmicContrast: 0.6285938215442002
purpose: []
